stages:
  - build
  - test

build:
  stage: build
  script:
    - cd "REST API"
    - ./gradlew build -x test --stacktrace
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd "REST API"
    - ./gradlew test
    - ./gradlew.bat --stop
